config/routes.rb
Rails.application.routes.draw do
  resources :isr_lists
  get 'override_call_lists/change'
  get 'override_call_lists/store'
  resources :override_call_lists
  resources :author_lists
  get 'call_lists/custname'
  get 'call_lists/multi'
  get 'call_lists/list'
  get 'call_lists/isr_week'
  get 'call_lists/isrlist'
  # get 'call_lists/rep_week'
  get 'call_lists/replist'
  get 'call_lists/selected'
  get 'call_lists/week_select'
  get 'call_lists/not_called'
  get 'call_lists/not_ordered'
  get 'call_lists/not_on_list'
  get 'call_lists/no_customer'
  get 'call_lists/all_customer'
  post 'call_days/import'
  resources :call_lists do
    collection { post :import }
    resources :call_days, except: [:index, :show]
  end
  devise_for :users, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'
end

app/models/author_list.rb
class AuthorList < ApplicationRecord
end

app/controllers/author_lists_controller.rb
class AuthorListsController < ApplicationController
  before_action :set_author_list, only: [:show, :edit, :update, :destroy]

  # GET /author_lists
  # GET /author_lists.json
  def index
    @author_lists = AuthorList.all
  end

  # GET /author_lists/1
  # GET /author_lists/1.json
  def show
  end

  # GET /author_lists/new
  def new
    @author_list = AuthorList.new
  end

  # GET /author_lists/1/edit
  def edit
  end

  # POST /author_lists
  # POST /author_lists.json
  def create
    @author_list = AuthorList.new(author_list_params)

    respond_to do |format|
      if @author_list.save
        format.html { redirect_to @author_list, notice: 'Author list was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /author_lists/1
  # PATCH/PUT /author_lists/1.json
  def update
    respond_to do |format|
      if @author_list.update(author_list_params)
        format.html { redirect_to @author_list, notice: 'Author list was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /author_lists/1
  # DELETE /author_lists/1.json
  def destroy
    @author_list.destroy
    respond_to do |format|
      format.html { redirect_to author_lists_url, notice: 'Author list was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author_list
      @author_list = AuthorList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_list_params
      params.require(:author_list).permit(:partcode, :dept, :custcode, :turns, :seq, :priority)
    end
end

app/helpers/author_lists_helper.rb
module AuthorListsHelper
end

app/views/author_lists/_form.html.erb
<%= form_with(model: author_list, local: true) do |form| %>
  <% if author_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author_list.errors.count, "error") %> prohibited this author_list from being saved:</h2>

      <ul>
      <% author_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :partcode %>
    <%= form.text_field :partcode, id: :author_list_partcode %>
  </div>

  <div class="field">
    <%= form.label :dept %>
    <%= form.text_field :dept, id: :author_list_dept %>
  </div>

  <div class="field">
    <%= form.label :custcode %>
    <%= form.text_field :custcode, id: :author_list_custcode %>
  </div>

  <div class="field">
    <%= form.label :turns %>
    <%= form.number_field :turns, id: :author_list_turns %>
  </div>

  <div class="field">
    <%= form.label :seq %>
    <%= form.number_field :seq, id: :author_list_seq %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority, id: :author_list_priority %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/author_lists/edit.html.erb
<h1>Editing Author List</h1>

<%= render 'form', author_list: @author_list %>

<%= link_to 'Show', @author_list %> |
<%= link_to 'Back', author_lists_path %>

app/views/author_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Author Lists</h1>

<table>
  <thead>
    <tr>
      <th>Partcode</th>
      <th>Dept</th>
      <th>Custcode</th>
      <th>Turns</th>
      <th>Seq</th>
      <th>Priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @author_lists.each do |author_list| %>
      <tr>
        <td><%= author_list.partcode %></td>
        <td><%= author_list.dept %></td>
        <td><%= author_list.custcode %></td>
        <td><%= author_list.turns %></td>
        <td><%= author_list.seq %></td>
        <td><%= author_list.priority %></td>
        <td><%= link_to 'Show', author_list %></td>
        <td><%= link_to 'Edit', edit_author_list_path(author_list) %></td>
        <td><%= link_to 'Destroy', author_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author List', new_author_list_path %>

app/views/author_lists/new.html.erb
<h1>New Author List</h1>

<%= render 'form', author_list: @author_list %>

<%= link_to 'Back', author_lists_path %>

app/views/author_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Partcode:</strong>
  <%= @author_list.partcode %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @author_list.dept %>
</p>

<p>
  <strong>Custcode:</strong>
  <%= @author_list.custcode %>
</p>

<p>
  <strong>Turns:</strong>
  <%= @author_list.turns %>
</p>

<p>
  <strong>Seq:</strong>
  <%= @author_list.seq %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @author_list.priority %>
</p>

<%= link_to 'Edit', edit_author_list_path(@author_list) %> |
<%= link_to 'Back', author_lists_path %>