config/routes.rb
Rails.application.routes.draw do
  resources :isr_lists
  get 'override_call_lists/change'
  get 'override_call_lists/store'
  resources :override_call_lists
  resources :author_lists
  get 'call_lists/custname'
  get 'call_lists/multi'
  get 'call_lists/list'
  get 'call_lists/isr_week'
  get 'call_lists/isrlist'
  # get 'call_lists/rep_week'
  get 'call_lists/replist'
  get 'call_lists/selected'
  get 'call_lists/week_select'
  get 'call_lists/not_called'
  get 'call_lists/not_ordered'
  get 'call_lists/not_on_list'
  get 'call_lists/no_customer'
  get 'call_lists/all_customer'
  post 'call_days/import'
  resources :call_lists do
    collection { post :import }
    resources :call_days, except: [:index, :show]
  end
  devise_for :users, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'
end

app/models/override_call_list.rb
class OverrideCallList < ApplicationRecord
end

app/controllers/override_call_lists_controller.rb
class OverrideCallListsController < ApplicationController
  before_action :set_override_call_list, only: [:show, :edit, :update, :destroy]

  # GET /override_call_lists
  def index
    @override_call_lists = OverrideCallList.all
  end

  # GET /override_call_lists/1
  def show
  end

  # GET /override_call_lists/new
  def new
    @override_call_list = OverrideCallList.new
  end

  # GET /override_call_lists/1/edit
  def edit
  end

  # POST /override_call_lists
  def create
    respond_to do |format|
      if @override_call_list.save
        format.html { redirect_to @override_call_list, notice: 'Override call list was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /override_call_lists/1
  def update
    @override_call_list = OverrideCallList.find(params[:id])
    if @override_call_list.update(override_call_list_params)
      redirect_to call_lists_path, notice: 'Override call list was successfully updated.'
    else
      render :change
    end
  end

  # DELETE /override_call_lists/1
  def destroy
    @override_call_list.destroy
    respond_to do |format|
      format.html { redirect_to override_call_lists_url, notice: 'Override call list was successfully destroyed.' }
    end
  end

  def change
    @override_call_list = OverrideCallList.find_by(custcode: params[:custcode])
    today = Date.today
    if @override_call_list.override_end < today
      # The override has lapsed so overwrite it with valuse from the base records
      call_list = CallList.find_by(custcode: params[:custcode])
      @override_call_list.custcode = call_list.custcode
      @override_call_list.custname = call_list.custname
      @override_call_list.contact_method = call_list.contact_method
      @override_call_list.contact = call_list.contact
      @override_call_list.phone = call_list.phone
      @override_call_list.email = call_list.email
      @override_call_list.selling = call_list.selling
      @override_call_list.main_phone = call_list.main_phone
      @override_call_list.website = call_list.website
      @override_call_list.rep = call_list.rep
    end

    @callday = ['SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY']
    @callback = [' ', 'SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY']
    @contact_method = ['CALL', 'EMAIL', 'TEXT']
    @called = ['NO', 'NO ANSWER', 'YES']
    @ordered = [' ', 'NO', 'YES']
    @windows = ['10am - noon', 'noon - 2pm', '2pm - 4pm', '4pm - 6pm']
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_override_call_list
      @override_call_list = OverrideCallList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def override_call_list_params
      params.require(:override_call_list).permit(:custcode, :custname, :contact_method, :contact, :phone, :email, :selling, :main_phone, :website, :rep, :override_start, :override_end)
    end
end

app/helpers/override_call_lists_helper.rb
module OverrideCallListsHelper
end

app/views/override_call_lists/_form.html.erb
<%= form_with(model: override_call_list, local: true) do |form| %>
  <fieldset>
    <legend><strong>Customer</strong></legend>
    <p>
      <table>
        <thead>
          <tr>
            <th> Code </th>
            <th> <%= form.label :custname, "Name" %> </th>
            <th> <%= form.label :contact, "Contact" %> </th>
            <th> <%= form.label :phone, "Phone" %> </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% if @override_call_list.custcode %>
              <td> <%= @override_call_list.custcode %> </td>
            <% else %>
              <td></td>
            <% end %>
            <td> <%= form.text_field :custname, size: 40, id: :override_call_list_custname %> </td>
            <td> <%= form.text_field :contact, size: 40, id: :override_call_list_contact %> </td>
            <td> <%= form.telephone_field :phone, size: 40, id: :override_call_list_phone %> </td>
          </tr>
        </tbody>
      </table>
      <table>
        <thead>
          <tr>
            <th> <%= form.label :main_phone, "Main phone" %> </th>
            <th> <%= form.label :email, "Email" %> </th>
            <th> <%= form.label :website, "Website" %> </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td> <%= form.telephone_field :main_phone, size: 20, id: :override_call_list_main_phone %> </td>
            <td> <%= form.text_field :email, size: 40, id: :override_call_list_email %> </td>
            <td> <%= form.text_field :website, size: 40, id: :override_call_list_website %> </td>
          </tr>
        </tbody>
      </table>
      <table>
        <thead>
          <tr>
            <th> <%= form.label :selling, "Selling" %> </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td> <%= form.text_field :selling, size: 50, id: :override_call_list_selling %> </td>
          </tr>
        </tbody>
      </table>
    </p>
  </fieldset>

  <table>
    <thead>
      <tr>
        <th> <%= form.label :override_start, "Start date" %> </th>
        <th> <%= form.label :override_end, "End date" %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.date_select :override_start, id: :override_call_list_override_start %> </td>
        <td> <%= form.date_select :override_end, id: :override_call_list_override_end %> </td>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/override_call_lists/change.html.erb
<h2>Editing Override</h2>

<%= render 'form', override_call_list: @override_call_list %>

app/views/override_call_lists/edit.html.erb
<h1>Override Call List</h1>

<%= render 'form', override_call_list: @override_call_list %>

<%= link_to 'Show', @override_call_list %> |
<%= link_to 'Back', override_call_lists_path %>

app/views/override_call_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Override Call Lists</h1>

<table>
  <thead>
    <tr>
      <th>Custcode</th>
      <th>Custname</th>
      <th>Contact method</th>
      <th>Contact</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Selling</th>
      <th>Main phone</th>
      <th>Website</th>
      <th>Rep</th>
      <th>Override start</th>
      <th>Override end</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @override_call_lists.each do |override_call_list| %>
      <tr>
        <td><%= override_call_list.custcode %></td>
        <td><%= override_call_list.custname %></td>
        <td><%= override_call_list.contact_method %></td>
        <td><%= override_call_list.contact %></td>
        <td><%= override_call_list.phone %></td>
        <td><%= override_call_list.email %></td>
        <td><%= override_call_list.selling %></td>
        <td><%= override_call_list.main_phone %></td>
        <td><%= override_call_list.website %></td>
        <td><%= override_call_list.rep %></td>
        <td><%= override_call_list.override_start %></td>
        <td><%= override_call_list.override_end %></td>
        <td><%= link_to 'Show', override_call_list %></td>
        <td><%= link_to 'Edit', edit_override_call_list_path(override_call_list) %></td>
        <td><%= link_to 'Destroy', override_call_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Override Call List', new_override_call_list_path %>

app/views/override_call_lists/new.html.erb
<h1>New Override Call List</h1>

<%= render 'form', override_call_list: @override_call_list %>

<%= link_to 'Back', override_call_lists_path %>

app/views/override_call_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Custcode:</strong>
  <%= @override_call_list.custcode %>
</p>

<p>
  <strong>Custname:</strong>
  <%= @override_call_list.custname %>
</p>

<p>
  <strong>Contact method:</strong>
  <%= @override_call_list.contact_method %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @override_call_list.contact %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @override_call_list.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @override_call_list.email %>
</p>

<p>
  <strong>Selling:</strong>
  <%= @override_call_list.selling %>
</p>

<p>
  <strong>Main phone:</strong>
  <%= @override_call_list.main_phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @override_call_list.website %>
</p>

<p>
  <strong>Rep:</strong>
  <%= @override_call_list.rep %>
</p>

<p>
  <strong>Override start:</strong>
  <%= @override_call_list.override_start %>
</p>

<p>
  <strong>Override end:</strong>
  <%= @override_call_list.override_end %>
</p>

<%= link_to 'Edit', edit_override_call_list_path(@override_call_list) %> |
<%= link_to 'Back', override_call_lists_path %>