config/routes.rb
Rails.application.routes.draw do
  resources :isr_lists
  get 'override_call_lists/change'
  get 'override_call_lists/store'
  resources :override_call_lists
  resources :author_lists
  get 'call_lists/custname'
  get 'call_lists/multi'
  get 'call_lists/list'
  get 'call_lists/isr_week'
  get 'call_lists/isrlist'
  # get 'call_lists/rep_week'
  get 'call_lists/replist'
  get 'call_lists/selected'
  get 'call_lists/week_select'
  get 'call_lists/not_called'
  get 'call_lists/not_ordered'
  get 'call_lists/not_on_list'
  get 'call_lists/no_customer'
  get 'call_lists/all_customer'
  post 'call_days/import'
  resources :call_lists do
    collection { post :import }
    resources :call_days, except: [:index, :show]
  end
  devise_for :users, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'
end

app/models/call_list.rb
class CallList < ApplicationRecord
  has_many :call_days, inverse_of: :call_list, :dependent => :destroy
  accepts_nested_attributes_for :call_days, reject_if: proc { |attributes| attributes['callday'].blank? }

  def self.import(file)
    CSV.foreach(file.path, headers:true, :encoding => 'windows-1251:utf-8') do |row|
      CallList.create! row.to_hash
    end
  end

  def user_is_isr(c)
    isr_match = false
    c.call_days.each do |d|
      if d.isr == current_user.email.upcase
        isr_match = true
      end
    end
    isr_match
  end

end

app/controllers/call_lists_controller.rb
class CallListsController < ApplicationController
  before_action :set_call_list, only: [:show, :edit, :update, :destroy]
  before_action :set_user_and_manager
  before_action :build_lists, only: [:new, :edit, :list, :index]
  before_action :build_call_list, only: [:index]
  before_action :reset_called_flag, only: [:index, :list]
  before_action :get_call_list, only: [:not_called, :not_ordered, :not_on_list, :no_customer]

  # GET /call_lists
  def index
    $title = 'Call Lists'
  end

  # GET /call_lists/1
  def show
    $title = 'Show Call List'
  end

  # GET /call_lists/new
  def new
    $title = 'Add Call List'
    @new = true
    @call_list = CallList.new
    if !@isr_user
      @call_list.call_days.build
    end
  end

  # GET /call_lists/1/edit
  def edit
    $title = 'Edit Call List'
    @new = false
    if !@isr_user
      @call_list.call_days.build
    end
  end

  # POST /call_lists
  def create
    $title = 'Add Call List'
    cp = call_list_params
    cp[:rep] = current_user.email.upcase
    @call_list = CallList.new(cp)

    respond_to do |format|
      if @call_list.save
        format.html { redirect_to @call_list, notice: 'Call list was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /call_lists/1
  def update
    $title = 'Edit Call List'
    cp = call_list_params
    i = 0
    @call_list.call_days.each do |c|
      if call_list_params[:call_days_attributes][i.to_s][:callback] && c.callback != call_list_params[:call_days_attributes][i.to_s][:callback] && call_list_params[:call_days_attributes][i.to_s][:callback] != ' '
        cp[:call_days_attributes][i.to_s][:callback_date] = Date.today
        cp[:call_days_attributes][i.to_s][:called] = 'NO'
      end
      if call_list_params[:call_days_attributes][i.to_s][:called] && c.called != call_list_params[:call_days_attributes][i.to_s][:called] && call_list_params[:call_days_attributes][i.to_s][:called] == 'YES'
        cp[:call_days_attributes][i.to_s][:date_called] = Date.today
      end
      if call_list_params[:call_days_attributes][i.to_s][:ordered] && c.ordered != call_list_params[:call_days_attributes][i.to_s][:ordered] && call_list_params[:call_days_attributes][i.to_s][:ordered] == 'YES'
        cp[:call_days_attributes][i.to_s][:date_ordered] = Date.today
      end
      i += 1
    end
    respond_to do |format|
      if @call_list.update(cp)
        format.html { redirect_to @call_list, notice: 'Call list was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /call_lists/1
  def destroy
    @call_list.destroy
    respond_to do |format|
      format.html { redirect_to call_lists_url, notice: 'Call list was successfully destroyed.' }
    end
  end

  def selected
    days = []
    days = session[:calllist_days]
    windows = []
    windows = session[:calllist_windows]
    days.each do |c|
      select_item = []
      select_item = c
      if params[:called_day] == select_item[1].to_s
        session[:called_day] = select_item[0]
        break
      end
    end
    windows.each do |c|
      select_item = []
      select_item = c
      if params[:called_window] == select_item[1].to_s
        session[:called_window] = select_item[0]
        break
      end
    end
    reps = []
    reps = session[:calllist_reps]
    reps.each do |r|
      select_item = []
      select_item = r
      if params[:called_rep] == select_item[1].to_s
        session[:called_rep] = select_item[0]
        break
      end
    end
    redirect_to action: "index"
  end

  def week_select
    reps = []
    reps = session[:calllist_reps]
    reps.each do |r|
      select_item = []
      select_item = r
      if params[:called_rep] == select_item[1].to_s
        session[:called_rep] = select_item[0]
        break
      end
    end
    redirect_to action: "list"
  end

  def import
    CallList.import(params[:file])
    # need to create an override record for each call list record
    calllist = CallList.all
    now = Date.today
    yesterday = now - 1
    calllist.each do |c|
      override = OverrideCallList.new
      override.custcode = c.custcode
      override.custname = c.custname
      override.contact_method = c.contact_method
      override.contact = c.contact
      override.phone = c.phone
      override.email = c.email
      override.selling = c.selling
      override.main_phone = c.main_phone
      override.website = c.website
      override.rep = c.rep
      override.override_start = yesterday
      override.override_end = yesterday
      override.save
    end
    redirect_to root_url, notice: "Call list imported."
  end

  def not_called
    $title = 'Not Contacted This Week'
  end

  def not_ordered
    $title = 'Not Ordered This Week'
  end

  def not_on_list
    $title = 'Active Customers Not On Call List'
    call_list = @report_list.sort_by{ |t| t.custcode }
    list = ActiveCustomer.where(rep: @user).to_a
    active_customer = list.sort_by{ |t| t.custcode }
    @missing_call_list = []
    custcode = ' '
    i = 0
    active_customer.each do |a|
      if call_list[i].custcode > a.custcode
        # no call list record for this active customer
        if custcode != a.custcode
          # unless there are multiple ship tos for the same customer
          @missing_call_list.push(a)
        end
      elsif call_list[i].custcode == a.custcode
        # only go to the next call list
        custcode = a.custcode
        i += 1
      else
        i += 1
      end
    end
  end

  def no_customer
    $title = 'Call Lists With No Active Customer'
    call_list = @report_list.sort_by{ |t| t.custcode }
    list = ActiveCustomer.where(rep: @user).to_a
    active_customer = list.sort_by{ |t| t.custcode }
    @missing_customer = []
    i = 0
    list_length = call_list.length
    active_customer.each do |a|
      if i < list_length
        if call_list[i].custcode < a.custcode
        # no active customer for this call list record
          @missing_customer.push(call_list[i])
          i += 1
        else call_list[i].custcode == a.custcode
          i += 1
        end
      else
        break
      end
    end
  end

  def all_customer
    $title = 'All Active Customers'
    customer_list = []
    user = User.find_by(email: current_user.email)
    if @user == user.manager_id.upcase
      # this is a manager so get all the ActiveCustomer data for the reps that report to them also
      users = User.where(manager_id: @user)
      users.each do |u|
        list = ActiveCustomer.where(rep: u.email.upcase).to_a
        list.each {|i| customer_list << i }
      end
    else
      customer_list = ActiveCustomer.where(rep: @user).to_a
    end
    report_list = customer_list.sort_by{ |t| t.custcode }
    customer = report_list[report_list.length - 1]
    @report_list = []
    report_list.each do |r|
      if r.custcode != customer.custcode
        @report_list.push(r)
      end
      customer = r
    end
    @call_list = []
    @found = false
    @report_list.each do |r|
      if CallList.exists?(custcode: r.custcode)
        call_exists = CallList.find_by(custcode: r.custcode)
        @call_list.push(call_exists)
      end
    end
  end

  def isrlist
    @isr = params[:isr]
    $title = "This Week's Call List For " + @isr
    $isr = params[:isr]
    call_days = CallDay.where(isr: @isr)
    @sunday_isrlist1 = []
    @sunday_isrlist2 = []
    @sunday_isrlist3 = []
    @sunday_isrlist4 = []
    @monday_isrlist1 = []
    @monday_isrlist2 = []
    @monday_isrlist3 = []
    @monday_isrlist4 = []
    @tuesday_isrlist1 = []
    @tuesday_isrlist2 = []
    @tuesday_isrlist3 = []
    @tuesday_isrlist4 = []
    @wednesday_isrlist1 = []
    @wednesday_isrlist2 = []
    @wednesday_isrlist3 = []
    @wednesday_isrlist4 = []
    @thursday_isrlist1 = []
    @thursday_isrlist2 = []
    @thursday_isrlist3 = []
    @thursday_isrlist4 = []
    @friday_isrlist1 = []
    @friday_isrlist2 = []
    @friday_isrlist3 = []
    @friday_isrlist4 = []
    call_days.each do |c|
      call_list = CallList.find(c.call_list_id)
      if !c.callback || c.callback == ' '
        # no callback
        case c.callday
        when 'MONDAY'
          case c.window
          when '10am - noon'
            @monday_isrlist1.push(call_list)
          when 'noon - 2pm'
            @monday_isrlist2.push(call_list)
          when '2pm - 4pm'
            @monday_isrlist3.push(call_list)
          else
            @monday_isrlist4.push(call_list)
          end
        when 'TUESDAY'
          case c.window
          when '10am - noon'
            @tuesday_isrlist1.push(call_list)
          when 'noon - 2pm'
            @tuesday_isrlist2.push(call_list)
          when '2pm - 4pm'
            @tuesday_isrlist3.push(call_list)
          else
            @tuesday_isrlist4.push(call_list)
          end
        when 'WEDNESDAY'
          case c.window
          when '10am - noon'
            @wednesday_isrlist1.push(call_list)
          when 'noon - 2pm'
            @wednesday_isrlist2.push(call_list)
          when '2pm - 4pm'
            @wednesday_isrlist3.push(call_list)
          else
            @wednesday_isrlist4.push(call_list)
          end
        when 'THURSDAY'
          case c.window
          when '10am - noon'
            @thursday_isrlist1.push(call_list)
          when 'noon - 2pm'
            @thursday_isrlist2.push(call_list)
          when '2pm - 4pm'
            @thursday_isrlist3.push(call_list)
          else
            @thursday_isrlist4.push(call_list)
          end
        when 'FRIDAY'
          case c.window
          when '10am - noon'
            @friday_isrlist1.push(call_list)
          when 'noon - 2pm'
            @friday_isrlist2.push(call_list)
          when '2pm - 4pm'
            @friday_isrlist3.push(call_list)
          else
            @friday_isrlist4.push(call_list)
          end
        end
      else
        # callback in force
        case c.callback

app/helpers/call_lists_helper.rb
module CallListsHelper
end

app/views/call_lists/edit.html.erb
<%= render 'form', call_list: @call_list %>

<%= link_to 'Show', @call_list %>
<%= link_to 'List', call_lists_path %>
<% if current_user.email == "admin" %>
  <%= link_to 'Week', call_lists_isrlist_path(isr: $isr) %>
<% end %>

app/views/call_lists/index.html.erb
<p id="notice"><%= notice %></p>


<%= form_with url: call_lists_selected_path, local: true, method: 'get' do |f| %>
  <table>
    <thead>
      <tr>
        <th> <%= f.label(:called_day, 'Day:') %> </th>
        <th> <%= f.select(:called_day, options_for_select(@day, @selected_day)) %> </th>
        <th> <%= f.label(:called_window, 'Window:') %> </th>
        <th> <%= f.select(:called_window, options_for_select(@window, @selected_window)) %> </th>
        <% if @manager %>
          <th> <%= f.label(:called_rep, 'Rep:') %> </th>
          <th> <%= f.select(:called_rep, options_for_select(@reps, @selected_rep)) %> </th>
        <% end %>
        <th> <%= f.submit "Change" %> </th>
      </tr>
    </thead>
  </table>

<% end %>

<% if !@isr_user %>
  <div class="button">
    <%= link_to 'Add Call List', new_call_list_path %>
  </div>
<% end %>

<table id="normal_dt"  class="stripe" class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <th>Custcode</th>
      <th>Custname</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Override</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @call_lists.each do |call_list| %>
      <tr>
        <td><%= call_list.custcode %></td>
        <td><%= call_list.custname %></td>
        <td><%= link_to 'Show', call_list %></td>
        <td><%= link_to 'Edit', edit_call_list_path(call_list) %></td>
        <td><%= link_to 'Override', override_call_lists_change_path(custcode: call_list.custcode) %></td>
        <td><%= link_to 'Delete', call_list, method: :delete, data: { confirm: 'Call list will be permanently removed. Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/call_lists/isr_week.html.erb
<p id="notice"><%= notice %></p>

<table id="normal_dt"  class="stripe" class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <th rowspan="2"> ISR </th>
      <th colspan="4"> Mon </th>
      <th colspan="4"> Tue </th>
      <th colspan="4"> Wed </th>
      <th colspan="4"> Thu </th>
      <th colspan="4"> Fri </th>
      <th rowspan="2"> Total </th>
    </tr>
    <tr>
      <th> 1 </th>
      <th> 2 </th>
      <th> 3 </th>
      <th> 4 </th>
      <th> 1 </th>
      <th> 2 </th>
      <th> 3 </th>
      <th> 4 </th>
      <th> 1 </th>
      <th> 2 </th>
      <th> 3 </th>
      <th> 4 </th>
      <th> 1 </th>
      <th> 2 </th>
      <th> 3 </th>
      <th> 4 </th>
      <th> 1 </th>
      <th> 2 </th>
      <th> 3 </th>
      <th> 4 </th>
    </tr>
  </thead>
  <tbody>
    <% @weekhash.each do |w| %>
    <tr>
      <td><%= link_to w[:isr], call_lists_isrlist_path(isr: w[:isr]) %></td>
      <td><%= w[:mon_1] %></td>
      <td><%= w[:mon_2] %></td>
      <td><%= w[:mon_3] %></td>
      <td><%= w[:mon_4] %></td>
      <td><%= w[:tue_1] %></td>
      <td><%= w[:tue_2] %></td>
      <td><%= w[:tue_3] %></td>
      <td><%= w[:tue_4] %></td>
      <td><%= w[:wed_1] %></td>
      <td><%= w[:wed_2] %></td>
      <td><%= w[:wed_3] %></td>
      <td><%= w[:wed_4] %></td>
      <td><%= w[:thu_1] %></td>
      <td><%= w[:thu_2] %></td>
      <td><%= w[:thu_3] %></td>
      <td><%= w[:thu_4] %></td>
      <td><%= w[:fri_1] %></td>
      <td><%= w[:fri_2] %></td>
      <td><%= w[:fri_3] %></td>
      <td><%= w[:fri_4] %></td>
      <td><%= w[:tot] %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/call_lists/isrlist.html.erb
<p id="notice"><%= notice %></p>
<table id="listtab" class="stripe" class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <th rowspan="2"> Row </th>
      <th colspan="4"> Mon </th>
      <th colspan="4"> Tue </th>
      <th colspan="4"> Wed </th>
      <th colspan="4"> Thu </th>
      <th colspan="4"> Fri </th>
    </tr>
    <tr>
      <th> 1 </th>
      <th> 2 </th>
      <th> 3 </th>
      <th> 4 </th>
      <th> 1 </th>
      <th> 2 </th>
      <th> 3 </th>
      <th> 4 </th>
      <th> 1 </th>
      <th> 2 </th>
      <th> 3 </th>
      <th> 4 </th>
      <th> 1 </th>
      <th> 2 </th>
      <th> 3 </th>
      <th> 4 </th>
      <th> 1 </th>
      <th> 2 </th>
      <th> 3 </th>
      <th> 4 </th>
    </tr>
  </thead>
  <tbody>
    <% i = 0 %>
    <% while i < @list_length %>
    <tr>
      <td><%= i+1 %></td>
      <% if i < @monday_isrlist1.length %>
        <td><%= link_to @monday_isrlist1[i].custname, edit_call_list_path(@monday_isrlist1[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @monday_isrlist2.length %>
        <td><%= link_to @monday_isrlist2[i].custname, edit_call_list_path(@monday_isrlist2[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @monday_isrlist3.length %>
        <td><%= link_to @monday_isrlist3[i].custname, edit_call_list_path(@monday_isrlist3[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @monday_isrlist4.length %>
        <td><%= link_to @monday_isrlist4[i].custname, edit_call_list_path(@monday_isrlist4[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @tuesday_isrlist1.length %>
        <td><%= link_to @tuesday_isrlist1[i].custname, edit_call_list_path(@tuesday_isrlist1[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @tuesday_isrlist2.length %>
        <td><%= link_to @tuesday_isrlist2[i].custname, edit_call_list_path(@tuesday_isrlist2[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @tuesday_isrlist3.length %>
        <td><%= link_to @tuesday_isrlist3[i].custname, edit_call_list_path(@tuesday_isrlist3[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @tuesday_isrlist4.length %>
        <td><%= link_to @tuesday_isrlist4[i].custname, edit_call_list_path(@tuesday_isrlist4[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @wednesday_isrlist1.length %>
        <td><%= link_to @wednesday_isrlist1[i].custname, edit_call_list_path(@wednesday_isrlist1[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @wednesday_isrlist2.length %>
        <td><%= link_to @wednesday_isrlist2[i].custname, edit_call_list_path(@wednesday_isrlist2[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @wednesday_isrlist3.length %>
        <td><%= link_to @wednesday_isrlist3[i].custname, edit_call_list_path(@wednesday_isrlist3[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @wednesday_isrlist4.length %>
        <td><%= link_to @wednesday_isrlist4[i].custname, edit_call_list_path(@wednesday_isrlist4[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @thursday_isrlist1.length %>
        <td><%= link_to @thursday_isrlist1[i].custname, edit_call_list_path(@thursday_isrlist1[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @thursday_isrlist2.length %>
        <td><%= link_to @thursday_isrlist2[i].custname, edit_call_list_path(@thursday_isrlist2[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @thursday_isrlist3.length %>
        <td><%= link_to @thursday_isrlist3[i].custname, edit_call_list_path(@thursday_isrlist3[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @thursday_isrlist4.length %>
        <td><%= link_to @thursday_isrlist4[i].custname, edit_call_list_path(@thursday_isrlist4[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @friday_isrlist1.length %>
        <td><%= link_to @friday_isrlist1[i].custname, edit_call_list_path(@friday_isrlist1[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @friday_isrlist2.length %>
        <td><%= link_to @friday_isrlist2[i].custname, edit_call_list_path(@friday_isrlist2[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @friday_isrlist3.length %>
        <td><%= link_to @friday_isrlist3[i].custname, edit_call_list_path(@friday_isrlist3[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if i < @friday_isrlist4.length %>
        <td><%= link_to @friday_isrlist4[i].custname, edit_call_list_path(@friday_isrlist4[i]) %></td>
      <% else %>
        <td></td>
      <% end %>
    </tr>
    <% i += 1 %>
  <% end %>
  </tbody>
</table>

app/views/call_lists/list.html.erb
<p id="notice"><%= notice %></p>


<% if @manager %>
  <%= form_with url: call_lists_week_select_path, local: true, method: 'get' do |f| %>
    <table>
      <thead>
        <tr>
          <th> <%= f.label(:called_rep, 'Rep:') %> </th>
          <th> <%= f.select(:called_rep, options_for_select(@reps, @selected_rep)) %> </th>
          <th> <%= f.submit "Change" %> </th>
        </tr>
      </thead>
    </table>
  <% end %>
<% end %>

<%= form_with url: call_lists_multi_path, local: true, method: 'get' do |f| %>

<table id="listtab" class="stripe" class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <th> Customer </th>
      <th> Sun </th>
      <th> Mon </th>
      <th> Tue </th>
      <th> Wed </th>
      <th> Thu </th>
      <th> Fri </th>
    </tr>
  </thead>
  <tbody>
    <% $call_lists.each do |call_list| %>
    <tr>
      <td><%= link_to call_list[:customer], edit_call_list_path(call_list[:calllist_id]) %></td>
      <% if call_list[:sun_id] %>
        <td> <%= f.select "sunday_isr_call_list[]", options_for_select(@isr_list, call_list[:sun_isr]) %> </td>
      <% else %>
        <td></td>
      <% end %>
      <% if call_list[:mon_id] %>
        <td> <%= f.select "monday_isr_call_list[]", options_for_select(@isr_list, call_list[:mon_isr]) %> </td>
      <% else %>
        <td></td>
      <% end %>
      <% if call_list[:tue_id] %>
        <td> <%= f.select "tuesday_isr_call_list[]", options_for_select(@isr_list, call_list[:tue_isr]) %> </td>
      <% else %>
        <td></td>
      <% end %>
      <% if call_list[:wed_id] %>
        <td> <%= f.select "wednesday_isr_call_list[]", options_for_select(@isr_list, call_list[:wed_isr]) %> </td>
      <% else %>
        <td></td>
      <% end %>
      <% if call_list[:thu_id] %>
        <td> <%= f.select "thursday_isr_call_list[]", options_for_select(@isr_list, call_list[:thu_isr]) %> </td>
      <% else %>
        <td></td>
      <% end %>
      <% if call_list[:fri_id] %>
        <td> <%= f.select "friday_isr_call_list[]", options_for_select(@isr_list, call_list[:fri_isr]) %> </td>
      <% else %>
        <td></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<%= f.submit "Submit" %>
<% end %>

app/views/call_lists/new.html.erb
<%= render 'form', call_list: @call_list %>

<%= link_to 'List', call_lists_path %>

app/views/call_lists/not_on_list.html.erb
<p id="notice"><%= notice %></p>

<table id="not_called"  class="stripe" class="mytable" class="display" cellspacing="0">
  <thead>
    <tr>
      <th> Customer </th>
      <th> Create call list </th>
    </tr>
  </thead>
  <tbody>
  <% @missing_call_list.each do |r| %>
    <tr>
      <td><%= r.custcode %></td>
      <td><%= link_to 'Add Call List', new_call_list_path %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/call_lists/show.html.erb
<p id="notice"><%= notice %></p>

<fieldset>
  <legend><strong>Customer</strong></legend>
  <table>
    <thead>
      <tr>
        <th> Code </th>
        <th> Name </th>
        <th> Contact </th>
        <th> Phone </th>
        <th> Main phone </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= @call_list.custcode %> </td>
        <td> <%= @call_list.custname %> </td>
        <td> <%= @call_list.contact %> </td>
        <td> <%= @call_list.phone %> </td>
        <td> <%= @call_list.main_phone %> </td>
      </tr>
    </tbody>
  </table>
  <table>
    <thead>
      <tr>
        <th> Email </th>
        <th> Website </th>
        <th> Selling </th>
        <th> Contact method </th>
        <th> Rep </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= @call_list.email %> </td>
        <td> <%= @call_list.website %> </td>
        <td> <%= @call_list.selling %> </td>
        <td> <%= @call_list.contact_method %> </td>
        <td> <%= @call_list.rep %> </td>
      </tr>
    </tbody>
  </table>
</fieldset>

<fieldset>
  <legend><strong>Communication</strong></legend>
  <table id="normal_dt"  class="stripe" class="mytable" class="display" cellspacing="0" >
    <thead>
      <tr>
        <th> Call day </th>
        <th> Window </th>
        <th> ISR </th>
        <th> Notes </th>
        <th> Called? </th>
        <th> Date called </th>
        <th> Ordered? </th>
        <th> Date ordered </th>
        <th> Alternative contact </th>
        <th> Callback </th>
        <th> Delete </th>
      </tr>
    </thead>
    <tbody>
      <% @call_list.call_days.each do |c| %>
      <tr>
        <td> <%= c.callday %> </td>
        <td> <%= c.window %> </td>
        <td> <%= c.isr %> </td>
        <td> <%= c.notes %> </td>
        <td> <%= c.called %> </td>
        <td> <%= display_date(c.date_called) %> </td>
        <td> <%= c.ordered %> </td>
        <td> <%= display_date(c.date_ordered) %> </td>
        <td> <%= c.alt_contact %> </td>
        <td> <%= c.callback %> </td>
        <td><%= link_to 'Delete', call_list_call_day_path(@call_list.id, c.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </fieldset>

<%= link_to 'Edit', edit_call_list_path(@call_list) %>
<%= link_to 'List', call_lists_path %>
<% if current_user.email == "admin" %>
  <%= link_to 'Week', call_lists_isrlist_path(isr: $isr) %>
<% end %>