config/routes.rb
Rails.application.routes.draw do
  resources :isr_lists
  get 'override_call_lists/change'
  get 'override_call_lists/store'
  resources :override_call_lists
  resources :author_lists
  get 'call_lists/custname'
  get 'call_lists/multi'
  get 'call_lists/list'
  get 'call_lists/isr_week'
  get 'call_lists/isrlist'
  # get 'call_lists/rep_week'
  get 'call_lists/replist'
  get 'call_lists/selected'
  get 'call_lists/week_select'
  get 'call_lists/not_called'
  get 'call_lists/not_ordered'
  get 'call_lists/not_on_list'
  get 'call_lists/no_customer'
  get 'call_lists/all_customer'
  post 'call_days/import'
  resources :call_lists do
    collection { post :import }
    resources :call_days, except: [:index, :show]
  end
  devise_for :users, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'
end

app/views/layouts/_header.html.erb
<h1 class="title"><%= $title %></h1>

<% if current_user %>
  <div id="navbar">
    <span><%= link_to 'Call List', call_lists_path %></span>
    <span><%= link_to 'Week', call_lists_list_path %></span>
    <span><%= link_to 'Password', edit_user_registration_path %></span>
    <% if current_user.email == "admin" %>
      <span><%= link_to 'Sign up', new_user_registration_path %></span>
      <span><%= link_to 'ISR Names', isr_lists_path %></span>
      <span><%= link_to 'ISR Week', call_lists_isr_week_path %></span>
    <% end %>
  </div>
  <div class="dropdown">
    <span class="dropbtn">Reports</span>
    <div class="dropdown-content">
      <span><%= link_to 'No Contact', call_lists_not_called_path %></span>
      <span><%= link_to 'Not Ordered', call_lists_not_ordered_path %></span>
      <span><%= link_to 'Not On Call List', call_lists_not_on_list_path %></span>
      <span><%= link_to 'All Customers', call_lists_all_customer_path %></span>
      <span><%= link_to 'Non-Active Customer', call_lists_no_customer_path %></span>
    </div>
  </div>
<% end %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FsCallList</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style="position: fixed; top: 0px; width: 100%; height: 4em; background-color: white; z-index: 100;">
      <%= render 'layouts/header' %>
    </div>
    <div style="margin-top: 4.5em;">
      <%= yield %>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
    <script src="/assets/printPreview.js"></script>
    <script src="/assets/myjavascript.js"></script>
  </body>
</html>